export default {
  SET_APP: "SET_APP",
  SET_SETTINGS: "SET_SETTINGS",
  SET_DARK_MODE: "SET_DARK_MODE",
  APP_LOADED: "APP_LOADED",
  DARK_MODE_LOADED: "DARK_MODE_LOADED",
  GET_APP: "GET_APP",
  REMOVE_APP: "REMOVE_APP",
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
  USER_LOADED: "USER_LOADED",
  RESET_RIDE: "RESET_RIDE",
  HIDE_RIDE_REVIEW: "HIDE_RIDE_REVIEW",
  SHOW_RIDE_REVIEW: "SHOW_RIDE_REVIEW",
  SET_CAN_CANCEL: "SET_CAN_CANCEL",
  SET_RIDE_CANCELED: "SET_RIDE_CANCELED",
  SET_BACKGROUND_PERMISSION: "SET_BACKGROUND_PERMISSION",
  REMOVE_BACKGROUND_PERMISSION: "REMOVE_BACKGROUND_PERMISSION",
  SET_ONGOING_RIDE: "SET_ONGOING_RIDE",
  SET_NEW_REQUEST_ID: "SET_NEW_REQUEST_ID",
  SET_RIDE_REQUEST_MESSAGE: "SET_RIDE_REQUEST_MESSAGE",

  // PARTNER
  SET_PARTNER: "SET_PARTNER",
  PARTNER_LOADED: "PARTNER_LOADED",
  SET_RIDE: "SET_RIDE",
  REMOVE_PARTNER: "REMOVE_PARTNER",

  // DOCUMENTS
  SET_UPLOAD_DOCUMENTS: "SET_UPLOAD_DOCUMENTS",
  // Socket events
  FOUND_DRIVER: "FOUND_DRIVER",
  DRIVER_ARRIVED: "DRIVER_ARRIVED",
  END_RIDE: "END_RIDE",
  REQUEST_DENIED: "REQUEST_DENIED",

  // Partner socket events
  NEW_REQUEST: "NEW_REQUEST",
  RESET_REQUEST: "RESET_REQUEST",
  CLEAR_RIDE: "CLEAR_RIDE",
  CANCEL_REQUEST: "CANCEL_REQUEST",
};
