export default {
    SET_APP: "SET_APP",
    APP_LOADED: "APP_LOADED",
    GET_APP: "GET_APP",
    REMOVE_APP: "REMOVE_APP",
    SET_USER: "SET_USER",
    GET_USER: "GET_USER",
    RESET_RIDE: "RESET_RIDE",
    SET_CAN_CANCEL: "SET_CAN_CANCEL",

    // PARTNER
    SET_PARTNER: "SET_PARTNER",
    SET_RIDE: "SET_RIDE",

    // Socket events
    FOUND_DRIVER: "FOUND_DRIVER",
    DRIVER_ARRIVED: "DRIVER_ARRIVED",
    END_RIDE: "END_RIDE",

    // Partner socket events
    NEW_REQUEST: "NEW_REQUEST",
    RESET_REQUEST: "RESET_REQUEST",
    CLEAR_RIDE: "CLEAR_RIDE",
    CANCEL_REQUEST: "CANCEL_REQUEST"
};
